<?php
function loginblock_theme($existing, $type, $theme, $path) {
  $hooks['user_login_block'] = array(
    'template' => 'user-login-block',
      'render element' => 'form',
    );
  return $hooks;
}

function loginblock_preprocess_user_login_block(&$vars) {

  // Modify the labels of the name and password form elements.
  $vars['form']['name']['#title'] = t('OUNetID or Username');
  $vars['form']['name']['#pass'] = t('Password');

  // Render the fields HTML for separate output
  $vars['name'] = render($vars['form']['name']);
  $vars['pass'] = render($vars['form']['pass']);
  $vars['submit'] = render($vars['form']['actions']['submit']);
  $vars['links'] = render($vars['form']['links']);
  $vars['rendered'] = drupal_render_children($vars['form']);

  // Provide a template suggestion
  if (!empty($vars['form']['#block'])) {
    $vars['theme_hook_suggestions'][] = 'user_login_block__' . $vars['form']['#block']->region;
  }
}
